
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>例外処理 &#8212; 仕事ですぐに使えるTypeScript  ドキュメント</title>
    <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/language_data.js"></script>
    <script type="text/javascript" src="_static/translations.js"></script>
    <link rel="index" title="索引" href="genindex.html" />
    <link rel="search" title="検索" href="search.html" />
    <link rel="next" title="モジュール" href="module.html" />
    <link rel="prev" title="非同期処理" href="async.html" />
   
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          

          <div class="body" role="main">
            
  <div class="section" id="id1">
<h1>例外処理<a class="headerlink" href="#id1" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>TypeScriptはJavaと似たような例外処理機構を備えています。ただし、ベースとなっているJavaScriptの言語の制約から、使い勝手などは多少異なります。</p>
<div class="section" id="typescript">
<h2>TypeScriptの例外処理構文<a class="headerlink" href="#typescript" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>A → B → Cと順番にタスクをこなすプログラムがあったとします。例えば、データを取得してきて、それを加工して、他のサーバーに送信するバッチ処理のプログラムとかを想像してください。
これが順番通りうまくいけば何も問題がありませんが、例えば、データ取得時や送信時にネットワークにうまく繋がらない、加工しようと思ったが、サーバーから送られてきたデータが想定と違ったなど、うまくいかないこともありえます。その場合に、処理を中断する（例外を投げる）、中断したことを察知して何かしらの対処をする（回復処理）を行います。これらの機構をまとめて例外処理と呼んだりします。</p>
<p><code class="docutils literal notranslate"><span class="pre">throw</span></code> を使って例外を投げます。 <code class="docutils literal notranslate"><span class="pre">throw</span></code> すると、その行でその関数やメソッド内部の処理は中断し、呼び出し元、そのさらに呼び出し元、と処理がどんどん巻き戻っていきます。最終的に回復処理を行う <code class="docutils literal notranslate"><span class="pre">try</span></code> 節/ <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節のペアにあたるまで巻き戻ります。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s2">&quot;ネットワークアクセス失敗&quot;</span><span class="p">);</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;この行は実行されない&quot;</span><span class="p">);</span>
</pre></div>
</div>
<p>例外を投げうる処理の周りは <code class="docutils literal notranslate"><span class="pre">try</span></code> 節で囲みます。 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節は例外が飛んできたときに呼ばれるコードブロックです。例外が発生してもしなくても、必ず通るのが <code class="docutils literal notranslate"><span class="pre">finally</span></code> 節です。後片付けの処理を書いたりします。
<code class="docutils literal notranslate"><span class="pre">finally</span></code> は省略できます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="kr">const</span> <span class="nx">data</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">getData</span><span class="p">();</span>
  <span class="kr">const</span> <span class="nx">modified</span> <span class="o">=</span> <span class="nx">modify</span><span class="p">(</span><span class="nx">data</span><span class="p">);</span>
  <span class="nx">await</span> <span class="nx">sendData</span><span class="p">(</span><span class="nx">modified</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`エラー発生 </span><span class="si">${</span><span class="nx">e</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span>
<span class="p">}</span> <span class="k">finally</span> <span class="p">{</span>
  <span class="c1">// 最後に必ず呼ばれる</span>
<span class="p">}</span>
</pre></div>
</div>
<p>もし、回復処理で回復仕切れない場合は、再度例外を投げることもできます。</p>
<div class="literal-block-wrapper docutils container" id="id9">
<div class="code-block-caption"><span class="caption-text">例外の再送</span><a class="headerlink" href="#id9" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="c1">//</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">throw</span> <span class="nx">e</span><span class="p">;</span> <span class="c1">// 再度投げる</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
<p>Javaの例外と似ていると最初に紹介しましたが、Javaと異なるのが、ベースのJavaScriptのコードは型情報をソースコード上に持っていないという点があります。
Javaの場合は、例外の <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節を複数持つことができ、それぞれの節に例外のクラスの種類を書いておくと、飛んできた例外の種類に応じて適切な節が選択されます。
JavaScriptでは1つしか書くことができません。型の種類による分岐というのも、 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節の中で <code class="docutils literal notranslate"><span class="pre">if</span></code> 文を使って行う必要があります。</p>
<p>例外クラスを自分で作る必要はありますが、Javaと同じことを実現するには、以下のようなコードになります。</p>
<div class="literal-block-wrapper docutils container" id="id10">
<div class="code-block-caption"><span class="caption-text">Javaと似たような例外の分岐</span><a class="headerlink" href="#id10" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="c1">// 何かしらの処理</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// instanceofを使ってエラーの種類を判別していく</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">e</span> <span class="k">instanceof</span> <span class="nx">NoNetworkError</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">// NoNetworkErrorの場合</span>
  <span class="p">}</span> <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="nx">e</span> <span class="k">instanceof</span> <span class="nx">NetworkAccessError</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">// NetworkAccessErrorの場合</span>
  <span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
    <span class="c1">// その他の場合</span>
  <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="error">
<h2><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラス<a class="headerlink" href="#error" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>例外処理で「問題が発生した」ときに情報伝達に使うのが <code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスです。
さきほどの構文は <code class="docutils literal notranslate"><span class="pre">new</span></code> と同時に <code class="docutils literal notranslate"><span class="pre">throw</span></code> していましたが、ふつうのオブジェクトです。</p>
<p><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスは作成時にメッセージの文字列を受け取れます。
<code class="docutils literal notranslate"><span class="pre">name</span></code> 属性にはクラス名、 <code class="docutils literal notranslate"><span class="pre">message</span></code> には作成時にコンストラクタに渡した文字列が格納されます。</p>
<p>JavaScriptの言語の標準に含まれていない、処理系独自の機能（といっても、今のところ全ブラウザで使える）のが、 <code class="docutils literal notranslate"><span class="pre">stack</span></code> プロパティに格納されるスタックトレースです。
<code class="docutils literal notranslate"><span class="pre">throw</span></code> した関数が今までどのように呼ばれてきたかの履歴です。ファイル名や行数も書かれていたりします。これがなければTypeScriptのデバッグは数万倍困難だったでしょう。</p>
<p>なお、この行数はTypeScriptをコンパイルした後のJavaScriptのファイル名と行番号だったりしますが、ソースマップというファイルをコンパイル時に出力しておき、実行時にそれがうまく読み込めると（ブラウザなら一緒にアップロード、Node.jsはnpmの <code class="docutils literal notranslate"><span class="pre">source-map-support</span></code> パッケージを利用すれば、もともとのTypeScriptのファイル名と行番号で出力されるようになります。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kr">const</span> <span class="nx">e</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;エラー発生&#39;</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`name: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">name</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span>
<span class="c1">// name: Error</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`message: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">message</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span>
<span class="c1">// message: エラー発生</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="sb">`stack: </span><span class="si">${</span><span class="nx">e</span><span class="p">.</span><span class="nx">stack</span><span class="si">}</span><span class="sb">`</span><span class="p">);</span>
<span class="c1">// stack: Error: test</span>
<span class="c1">//   at new MyError (&lt;anonymous&gt;:17:23)</span>
<span class="c1">//   at &lt;anonymous&gt;:23:9</span>
</pre></div>
</div>
<div class="section" id="id2">
<h3>標準の例外クラス<a class="headerlink" href="#id2" title="このヘッドラインへのパーマリンク">¶</a></h3>
<p>それ以外にも、いろいろな例外のためのクラスがあります。TypeScriptを使っているとコンパイル前に多くの問題を潰せるため、遭遇する回数はJavaScriptよりも減ります。</p>
<ul class="simple">
<li><p><code class="docutils literal notranslate"><span class="pre">EvalError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">RangeError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">ReferenceError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">TypeError</span></code></p></li>
<li><p><code class="docutils literal notranslate"><span class="pre">URIError</span></code></p></li>
</ul>
<p>例外を受け取って何もしない（俗称：例外を握りつぶす）は行儀がよくないコードとされますが、JSONパース時には文法がおかしい場合に <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> が発生します。 <code class="docutils literal notranslate"><span class="pre">JSON.parse()</span></code> だけは拾って無効値で初期化という処理は頻繁に行うでしょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kd">let</span> <span class="nx">json</span>: <span class="kt">any</span><span class="p">;</span>
<span class="k">try</span> <span class="p">{</span>
  <span class="nx">json</span> <span class="o">=</span> <span class="nx">JSON</span><span class="p">.</span><span class="nx">parse</span><span class="p">(</span><span class="nx">jsonString</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">json</span> <span class="o">=</span> <span class="kc">null</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</div>
<p>あとはブラウザの <code class="docutils literal notranslate"><span class="pre">fetch()</span></code> 関数でサーバー側のAPIにアクセスするときに、ネットワークエラー（corsでの権限がない場合も）は <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> が発生します。
<code class="docutils literal notranslate"><span class="pre">fetch</span></code> はJSONをパースする場合に <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> も発生します。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="kr">const</span> <span class="nx">res</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">fetch</span><span class="p">(</span><span class="s2">&quot;/api/users&quot;</span><span class="p">);</span> <span class="c1">// ここでTypeError発生の可能性</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">res</span><span class="p">.</span><span class="nx">ok</span><span class="p">)</span> <span class="p">{</span>
    <span class="kr">const</span> <span class="nx">json</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">res</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span>         <span class="c1">// ここでSyntaxError発生の可能性</span>
  <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<p>よくやりがちなのが、 <code class="docutils literal notranslate"><span class="pre">ok</span></code> の確認をしない（ステータスコードが200以外でJSON以外が帰ってきているときに）JSONをパースしようとしてエラーになることです。
<code class="docutils literal notranslate"><span class="pre">404</span> <span class="pre">Not</span> <span class="pre">Found</span></code> のときは、ボディが <code class="docutils literal notranslate"><span class="pre">Not</span> <span class="pre">Found</span></code> というテキストになるので、未知のトークン <code class="docutils literal notranslate"><span class="pre">N</span></code> というエラーになります。あとは403 Forbiddenのときには、未知のトークン <code class="docutils literal notranslate"><span class="pre">F</span></code> のエラーが発生します。</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>SyntaxError: Unexpected token N in JSON at position 0
</pre></div>
</div>
</div>
</div>
<div class="section" id="id3">
<h2>例外処理とコードの読みやすさ<a class="headerlink" href="#id3" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>例外処理も、コードを読む人の理解を手助けするための、ちょっとしたコツがあります。</p>
<div class="section" id="try">
<h3><code class="docutils literal notranslate"><span class="pre">try</span></code> 節はなるべく狭くする<a class="headerlink" href="#try" title="このヘッドラインへのパーマリンク">¶</a></h3>
<p>「この関数を呼ぶと、AとBの例外が飛んでくる可能性がある」というのはできあがったソースコードを見ても情報はわかりません。
次のコード例を見ても、AからEのどこでどんな例外が飛んでくるかわからないでしょう。</p>
<div class="literal-block-wrapper docutils container" id="id11">
<div class="code-block-caption"><span class="caption-text">広すぎるtryは例外の出どころをわかりにくくする</span><a class="headerlink" href="#id11" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="nx">logicA</span><span class="p">();</span>
  <span class="nx">logicB</span><span class="p">();</span>
  <span class="nx">logicC</span><span class="p">();</span>
  <span class="nx">logicD</span><span class="p">();</span>
  <span class="nx">logicE</span><span class="p">();</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// エラー処理</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
<p>なるべく狭くすることで、どの処理がどの例外を投げるのかが明確になります。</p>
<div class="literal-block-wrapper docutils container" id="id12">
<div class="code-block-caption"><span class="caption-text">tryの範囲を狭めると、どこで何がおきるのかがわかりやすくなる</span><a class="headerlink" href="#id12" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="nx">logicA</span><span class="p">();</span>
<span class="nx">logicB</span><span class="p">();</span>
<span class="k">try</span> <span class="p">{</span>
  <span class="nx">logicC</span><span class="p">();</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// エラー処理</span>
<span class="p">}</span>
<span class="nx">logicD</span><span class="p">();</span>
<span class="nx">logicE</span><span class="p">();</span>
</pre></div>
</div>
</div>
<p>実際に実行時に例外が起きうる（どんなにデバッグしても例外を抑制できない）ポイントは、外部の通信とかごく一部のはずです。あまりたくさん例外処理を書く必要もないと思いますし、書く場合もどこに書いたかがわかりやすくなります。</p>
<p>広くする問題としては、原因の違う例外が混ざってしまう点もあります。例えば、JSONのパースを何箇所かで行なっていると、それぞれの箇所で <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code> が投げられる可能性が出てきます。原因が違ってリカバリー処理が別の例外が同じ <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節に入ってきてしまうと</p>
</div>
<div class="section" id="error-throw">
<h3><code class="docutils literal notranslate"><span class="pre">Error</span></code> 以外を <code class="docutils literal notranslate"><span class="pre">throw</span></code> しない<a class="headerlink" href="#error-throw" title="このヘッドラインへのパーマリンク">¶</a></h3>
<p>前述の <code class="docutils literal notranslate"><span class="pre">catch</span></code> 文のサンプルでは、 <code class="docutils literal notranslate"><span class="pre">e</span></code> の型が <code class="docutils literal notranslate"><span class="pre">Error</span></code> という前提で書いていました。これにより、 <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節の中でコード補完がきくので、開発はしやすくなります。しかし、実際には、どの型がくるかは実行時の <code class="docutils literal notranslate"><span class="pre">throw</span></code> 次第です。 <code class="docutils literal notranslate"><span class="pre">throw</span></code> には <code class="docutils literal notranslate"><span class="pre">Error</span></code> 関連のクラス以外にも、文字列とか数値とかなんでも投げることができるからです。</p>
<p>基本的には <code class="docutils literal notranslate"><span class="pre">Error</span></code> 関連のオブジェクトだけを <code class="docutils literal notranslate"><span class="pre">throw</span></code> するようにしましょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="o">:</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// e.とタイプすると、name, messageなどがサジェストされる</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">name</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id4">
<h2>リカバリー処理の分岐のためにユーザー定義の例外クラスを作る<a class="headerlink" href="#id4" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>例外処理のためにクラスを作ってみましょう。 <code class="docutils literal notranslate"><span class="pre">Error</span></code> を継承することで、例外クラスを作ることができます。ただし、少し <code class="docutils literal notranslate"><span class="pre">Error</span></code> クラスは特殊なので、いくつかの追加処理をコンストラクタで行う必要があります。5個例外クラスを作るとして、全部のクラスで同じ処理を書くこともできます。しかし、これが10個とか20個になると大変です。1つのベースのクラスを作り、実際にコード中で扱うクラスはこれから継承して作るようにします。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="c1">// 共通エラークラス</span>
<span class="kr">class</span> <span class="nx">BaseError</span> <span class="kr">extends</span> <span class="nb">Error</span> <span class="p">{</span>
  <span class="kr">constructor</span><span class="p">(</span><span class="nx">e?</span>: <span class="kt">string</span><span class="p">)</span> <span class="p">{</span>
    <span class="kr">super</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
    <span class="k">this</span><span class="p">.</span><span class="nx">name</span> <span class="o">=</span> <span class="k">new</span><span class="p">.</span><span class="nx">target</span><span class="p">.</span><span class="nx">name</span><span class="p">;</span>
    <span class="c1">// 下記の行はTypeScriptの出力ターゲットがES2015より古い場合(ES3, ES5)のみ必要</span>
    <span class="nb">Object</span><span class="p">.</span><span class="nx">setPrototypeOf</span><span class="p">(</span><span class="k">this</span><span class="p">,</span> <span class="k">new</span><span class="p">.</span><span class="nx">target</span><span class="p">.</span><span class="nx">prototype</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">}</span>

<span class="c1">// BaseErrorを継承して、新しいエラーを作る</span>
<span class="c1">// statusCode属性にHTTPのステータスコードが格納できるように</span>
<span class="kr">class</span> <span class="nx">NetworkAccessError</span> <span class="kr">extends</span> <span class="nx">BaseError</span> <span class="p">{</span>
  <span class="kr">constructor</span><span class="p">(</span><span class="kr">public</span> <span class="nx">statusCode</span>: <span class="kt">number</span><span class="p">,</span> <span class="nx">e?</span>: <span class="kt">string</span><span class="p">)</span> <span class="p">{</span>
    <span class="kr">super</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">}</span>

<span class="c1">// 追加の属性がなければ、コンストラクタも定義不要</span>
<span class="kr">class</span> <span class="nx">NoNetworkError</span> <span class="kr">extends</span> <span class="nx">BaseError</span> <span class="p">{}</span>
</pre></div>
</div>
<p>このようにクラスをいくつも作ると、例外を受け取った <code class="docutils literal notranslate"><span class="pre">catch</span></code> 節で、リカバリーの方法を「選ぶ」ことが可能になります。
投げられたクラスごとに <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> と組み合わせて条件分岐に使えます。また、この <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> は型ガードになっていますので、各ブロックの中でコード補完も正しく行われます。
上記のクラスの <code class="docutils literal notranslate"><span class="pre">statusCode</span></code> も正しく補完されます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="nx">await</span> <span class="nx">getUser</span><span class="p">();</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">e</span> <span class="k">instanceof</span> <span class="nx">NoNetworkError</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;ネットワークがありません&quot;</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="nx">e</span> <span class="k">instanceof</span> <span class="nx">NetworkAccessError</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">// この節では、eはNetworkAccessErrorのインスタンスなので、</span>
    <span class="c1">// ↓のe.をタイプすると、statusCodeがサジェストされる</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">statusCode</span> <span class="o">&lt;</span> <span class="mi">500</span><span class="p">)</span> <span class="p">{</span>
      <span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;プログラムにバグがあります&quot;</span><span class="p">);</span>
    <span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
      <span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;サーバーエラー&quot;</span><span class="p">);</span>
    <span class="p">}</span>
  <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<p>なお、TypeScriptは、昔のJavaのように継承を前提とした処理を書くことはほとんどありませんので、コードの中で継承を使うことも極めてまれです。Javaの場合は、 <code class="docutils literal notranslate"><span class="pre">IOException</span></code> クラスを継承したクラスがあって、入出力系のエラーなど継承階層を前提としたコードが書かれたりもしました。しかし、これは「AはBの子クラスである」という知識を持っていないと読めないコードになってしまうため、プロジェクトに入ってきたばかりの人には混乱を与えがちです。例外クラスを作る場合も、 <code class="docutils literal notranslate"><span class="pre">BaseClass</span></code> からの直系の子供クラスだけで作れば問題ありません。立派な継承ツリーの設計は不要です。あまり例外クラスが多くても使い分けに迷ったりします。</p>
<div class="admonition note">
<p class="admonition-title">注釈</p>
<p>ターゲットがES3/ES5のときに <code class="docutils literal notranslate"><span class="pre">Object.setPrototypeOf(this,</span> <span class="pre">new.target.prototype);</span></code> の行を書き忘れると、 <code class="docutils literal notranslate"><span class="pre">instanceof</span></code> が <code class="docutils literal notranslate"><span class="pre">false</span></code> を返してくるようになります。</p>
</div>
</div>
<div class="section" id="id5">
<h2>例外処理を使わないエラー処理<a class="headerlink" href="#id5" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>正常に実行できなかったからといって、なんでも例外として処理しなければならないわけではありません。
例えば、ブラウザ標準の <code class="docutils literal notranslate"><span class="pre">fetch</span></code> APIの場合、通信ができたが、正常に終わらなかった場合は <code class="docutils literal notranslate"><span class="pre">ok</span></code> 属性を使って判断できます。
例外には深い階層から一発で離脱できる（途中の関数では、エラーがあったかどうかを判定不要）メリットがあります。
しかし、階層が深くなく、呼び出し元と例外処理を行うコードがすごく近い場合には、この <code class="docutils literal notranslate"><span class="pre">ok</span></code> のような属性を用意する方が管理もしやすいでしょう。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kr">const</span> <span class="nx">res</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">fetch</span><span class="p">(</span><span class="s2">&quot;/users&quot;</span><span class="p">);</span>
<span class="k">if</span> <span class="p">(</span><span class="nx">res</span><span class="p">.</span><span class="nx">ok</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// ステータスコードが200/300番台</span>
<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
  <span class="c1">// 400番以降</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
<div class="section" id="id6">
<h2>非同期と例外処理<a class="headerlink" href="#id6" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>非同期処理で難しいのがエラー処理でした。
<code class="docutils literal notranslate"><span class="pre">async</span></code> と <code class="docutils literal notranslate"><span class="pre">await</span></code> のおかげで例外処理もだいぶ書きやすくなりました。</p>
<p><code class="docutils literal notranslate"><span class="pre">Promise</span></code> では <code class="docutils literal notranslate"><span class="pre">then()</span></code> の2つめのコールバック関数でエラー処理が書けるようになりました。
また、エラー処理の節だけを書く <code class="docutils literal notranslate"><span class="pre">catch()</span></code> 節もあります。
複数の <code class="docutils literal notranslate"><span class="pre">then()</span></code> 節が連なっていても、1箇所だけエラー処理を書けば大丈夫です。
なお、一箇所もエラー処理を書かずにいて、エラーが発生すると <code class="docutils literal notranslate"><span class="pre">unhandledRejection</span></code> というエラーがNode.jsのコンソールに表示されることになります。</p>
<div class="literal-block-wrapper docutils container" id="id13">
<div class="code-block-caption"><span class="caption-text">Promiseのエラー書き方</span><a class="headerlink" href="#id13" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-js notranslate"><div class="highlight"><pre><span></span><span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">).</span><span class="nx">then</span><span class="p">(</span><span class="nx">resp</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="k">return</span> <span class="nx">resp</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span>
<span class="p">}).</span><span class="nx">then</span><span class="p">(</span><span class="nx">json</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">json</span><span class="p">);</span>
<span class="p">}).</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;エラー発生!&quot;</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
<span class="p">});</span>
</pre></div>
</div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">async</span></code> 関数の場合はもっとシンプルで、何かしらの非同期処理を実行する場合、 <code class="docutils literal notranslate"><span class="pre">await</span></code> していれば、通常の <code class="docutils literal notranslate"><span class="pre">try</span></code> 文でエラーを捕まえることができます。</p>
<div class="literal-block-wrapper docutils container" id="id14">
<div class="code-block-caption"><span class="caption-text">async関数内部のエラー処理の書き方</span><a class="headerlink" href="#id14" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="k">try</span> <span class="p">{</span>
  <span class="kr">const</span> <span class="nx">resp</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">);</span>
  <span class="kr">const</span> <span class="nx">json</span> <span class="o">=</span> <span class="nx">await</span> <span class="nx">resp</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">json</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span>: <span class="kt">Error</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s2">&quot;エラー発生!&quot;</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
</div>
<p>エラーを発生させるには、　<code class="docutils literal notranslate"><span class="pre">Promise</span></code> 作成時のコールバック関数の2つめの引数の <code class="docutils literal notranslate"><span class="pre">reject()</span></code> コールバック関数に <code class="docutils literal notranslate"><span class="pre">Error</span></code> オブジェクトを渡しても良いですし、
<code class="docutils literal notranslate"><span class="pre">then()</span></code> 節の中で例外をスローしても発生させることができます。</p>
<div class="highlight-ts notranslate"><div class="highlight"><pre><span></span><span class="kr">const</span> <span class="nx">heavyTask</span> <span class="o">=</span> <span class="nx">async</span> <span class="p">()</span><span class="o">:</span> <span class="nx">Promise</span><span class="o">&lt;</span><span class="kt">number</span><span class="o">&gt;</span> <span class="o">=&gt;</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nx">Promise</span><span class="o">&lt;</span><span class="kt">number</span><span class="o">&gt;</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="c1">// 何かしらの処理</span>
    <span class="nx">reject</span><span class="p">(</span><span class="nx">error</span><span class="p">);</span>
    <span class="c1">// こちらでもPromiseのエラーを発生可能</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">();</span>
  <span class="p">});</span>
<span class="p">};</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">Promise</span></code> 以前は非同期処理の場合は、コールバック関数の先頭の引数がエラー、という暗黙のルールで実装されていました。
ただし、1つのコールバックでも <code class="docutils literal notranslate"><span class="pre">return</span></code> を忘れると動作しませんし、通常の例外が発生して <code class="docutils literal notranslate"><span class="pre">return</span></code> されなかったりすると、コールバックの伝搬が中断されてしまいます。</p>
<div class="literal-block-wrapper docutils container" id="id15">
<div class="code-block-caption"><span class="caption-text">原始時代の非同期のエラー処理の書き方</span><a class="headerlink" href="#id15" title="このコードへのパーマリンク">¶</a></div>
<div class="highlight-js notranslate"><div class="highlight"><pre><span></span><span class="c1">// 旧: Promise以前</span>
<span class="nx">func1</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span> <span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span> <span class="nx">value</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="k">return</span> <span class="nx">err</span><span class="p">;</span>
  <span class="nx">func2</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span> <span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span> <span class="nx">value</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="k">return</span> <span class="nx">err</span><span class="p">;</span>
    <span class="nx">func3</span><span class="p">(</span><span class="nx">引数</span><span class="p">,</span> <span class="kd">function</span><span class="p">(</span><span class="nx">err</span><span class="p">,</span> <span class="nx">value</span><span class="p">)</span> <span class="p">{</span>
      <span class="c1">// 最後に実行されるコードブロック</span>
    <span class="p">});</span>
  <span class="p">});</span>
<span class="p">});</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id7">
<h2>例外とエラーの違い<a class="headerlink" href="#id7" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>この手の話になると、エラーと例外の違いとか、こっちはハンドリングするもの、こっちはOSにそのまま流すものとかいろんな議論が出てきます。例外とエラーの違いについても、コンセンサスは取れておらず、人によって意味が違ったりします。一例としては、回復可能なものがエラーで、そうじゃないものが例外といったことが言われたりします。このエントリーではエラーも例外も差をつけずに、全部例外とひっくるめて説明します。</p>
<p>例外というのはすべて、何かしらのリカバリーを考える必要があります。</p>
<ul>
<li><p>ちょっとしたネットワークのエラーなので、3回ぐらいはリトライしてみる</p>
<blockquote>
<div><ul class="simple">
<li><p>原因: ネットワークエラー</p></li>
<li><p>リカバリー: リトライ</p></li>
</ul>
</div></blockquote>
</li>
<li><p>サーバーにリクエストを送ってみたら400エラーが帰ってきた</p>
<blockquote>
<div><ul class="simple">
<li><p>原因: リクエストが不正</p></li>
<li><p>リカバリー(開発時): 本来のクライアントのロジックであればバリデーションで弾いていないといけないのでこれは潰さないといけない実装バグ。とりあえずスタックトレースとかありったけの情報をconsole.logに出しておく。</p></li>
<li><p>リカバリー(本番): ありえないバグが出た、とりあえず中途半端に継続するのではなくて、システムエラー、開発者に連絡してくれ、というメッセージをユーザーに出す（人力リカバリー）</p></li>
</ul>
</div></blockquote>
</li>
<li><p>JSONをパースしたら <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code></p>
<blockquote>
<div><ul class="simple">
<li><p>原因: ユーザーの入力が不正</p></li>
<li><p>リカバリー: フォームにエラーメッセージを出す</p></li>
</ul>
</div></blockquote>
</li>
</ul>
<p>最終的には、実装ミスなのか、ユーザーが間違ってデータ入力したという実行時の値の不正なのか、ネットワークの接続がおかしい、クラウドサービスの秘密鍵が合わないみたいな環境の問題なのか、どれであったとしても、システムが自力でリカバリーする、ユーザーに通知して入力修正やWiFiのある環境で再実行などの人力リカバリーしてもらう、開発者に通知してプログラム修正するといった人力リカバリーなど、何かしらのリカバリーは絶対必要になります。</p>
<p>Node.jsで <code class="docutils literal notranslate"><span class="pre">async</span></code> / <code class="docutils literal notranslate"><span class="pre">await</span></code> やら <code class="docutils literal notranslate"><span class="pre">Promise</span></code> を一切使っていないコードの場合、エラーを無視すると、Node.js自体が最後に <code class="docutils literal notranslate"><span class="pre">catch</span></code> して、エラー詳細を表示してプログラムが終了します。これはある意味プログラムとしては作戦放棄ではありますが、「プログラムの進行が不可能なので、OSに処理を返す」というリカバリーと言えなくもないでしょう。開発者にスタックトレースを表示して後を託す、というのも立派なリカバリーの戦術の1つです。</p>
<p>ブラウザの場合、誰もキャッチしないと、開発者ツールのコンソールに表示されますが、開発者ツールを開いていない限りエラーを見ることはできません。ユーザーには正常に正常に処理が進んだのか、そうじゃなかったのかわかりませんので、かならずキャッチして画面に表示してあげる必要があるでしょう。</p>
<p>どちらにしても何かしらのリカバリー処理が必要となりますので、本書ではエラーと例外の区別といったことはしません。</p>
</div>
<div class="section" id="id8">
<h2>まとめ<a class="headerlink" href="#id8" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>例外についての文法の説明、組み込みのエラー型、エラー型を自作する方法、非同期処理の例外処理などを説明してきました。
例外の設計も、一種のアーキテクチャ設計であるため、ちょっとした経験が必要になるかもしれません。</p>
<p>TypeScript、特にフロントエンドの場合、例外を無視することはユーザーの使い勝手を悪くします。どのようなことが発生し、どのケースではどのようにリカバリーするか、というのをあらかじめ決めておくと実装は楽になるでしょう。</p>
</div>
</div>


          </div>
          
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="index.html">目次</a></h3>
  <ul>
<li><a class="reference internal" href="#">例外処理</a><ul>
<li><a class="reference internal" href="#typescript">TypeScriptの例外処理構文</a></li>
<li><a class="reference internal" href="#error"><code class="docutils literal notranslate"><span class="pre">Error</span></code> クラス</a><ul>
<li><a class="reference internal" href="#id2">標準の例外クラス</a></li>
</ul>
</li>
<li><a class="reference internal" href="#id3">例外処理とコードの読みやすさ</a><ul>
<li><a class="reference internal" href="#try"><code class="docutils literal notranslate"><span class="pre">try</span></code> 節はなるべく狭くする</a></li>
<li><a class="reference internal" href="#error-throw"><code class="docutils literal notranslate"><span class="pre">Error</span></code> 以外を <code class="docutils literal notranslate"><span class="pre">throw</span></code> しない</a></li>
</ul>
</li>
<li><a class="reference internal" href="#id4">リカバリー処理の分岐のためにユーザー定義の例外クラスを作る</a></li>
<li><a class="reference internal" href="#id5">例外処理を使わないエラー処理</a></li>
<li><a class="reference internal" href="#id6">非同期と例外処理</a></li>
<li><a class="reference internal" href="#id7">例外とエラーの違い</a></li>
<li><a class="reference internal" href="#id8">まとめ</a></li>
</ul>
</li>
</ul>
<div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation overview</a><ul>
      <li>Previous: <a href="async.html" title="前の章へ">非同期処理</a></li>
      <li>Next: <a href="module.html" title="次の章へ">モジュール</a></li>
  </ul></li>
</ul>
</div>
  <div role="note" aria-label="source link">
    <h3>このページ</h3>
    <ul class="this-page-menu">
      <li><a href="_sources/exception.rst.txt"
            rel="nofollow">ソースコードを表示</a></li>
    </ul>
   </div><div>
    <h4>Page Info</h4>
    <p>
    <ul>
        <li>英数記号: 3790</li>
        <li>非アスキー: 5333</li>
        <li>合計文字数: 9123</li>
        <li>半角換算: 14456</li>
        <li>全角換算: 7228.0</li>
    </ul>
    </p>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3 id="searchlabel">クイック検索</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" aria-labelledby="searchlabel" />
      <input type="submit" value="検索" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;2019, Future Corporation.
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 2.2.1</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.12</a>
      
      |
      <a href="_sources/exception.rst.txt"
          rel="nofollow">Page source</a>
    </div>

    

    
  </body>
</html>